-- uji-content — datos: Tema 9 "El personal de las Cortes Generales (I)"
-- Generado a partir del PDF. Idempotente vía los INSERT ... ON DUPLICATE KEY / borrado previo de nodos.
-- Prefijo asumido: opouj_wp_

SET NAMES utf8mb4;

INSERT INTO opouj_wp_uji_temarios (slug, nombre, descripcion)
VALUES ('ujier-cortes-generales', 'Oposición Ujier de las Cortes Generales', 'Temario de la oposición al Cuerpo de Ujieres de las Cortes Generales.')
ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

INSERT INTO opouj_wp_uji_temas (temario_id, numero, titulo, slug, estado, fuente_pdf, orden)
SELECT id, 9, 'El personal de las Cortes Generales (I)', 'tema-9-personal-cortes-generales-i', 'publicado', 'Tema9.pdf', 9
FROM opouj_wp_uji_temarios WHERE slug = 'ujier-cortes-generales'
ON DUPLICATE KEY UPDATE titulo = VALUES(titulo), estado = VALUES(estado), fuente_pdf = VALUES(fuente_pdf);

-- Reseeding idempotente: fuera los nodos anteriores de este tema antes de reinsertar.
DELETE n FROM opouj_wp_uji_nodos n
INNER JOIN opouj_wp_uji_temas t ON t.id = n.tema_id
INNER JOIN opouj_wp_uji_temarios tm ON tm.id = t.temario_id
WHERE tm.slug = 'ujier-cortes-generales' AND t.numero = 9;

-- A partir de aquí usamos variables de sesión de MySQL como "punteros" a los ids
-- que se acaban de insertar (autoincrementales), para no tener que conocerlos de antemano.
SET @tema_id := (
  SELECT t.id FROM opouj_wp_uji_temas t
  INNER JOIN opouj_wp_uji_temarios tm ON tm.id = t.temario_id
  WHERE tm.slug = 'ujier-cortes-generales' AND t.numero = 9
);

-- ================= SECCIÓN 1. Introducción
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, color_clase, titulo, orden)
VALUES (@tema_id, NULL, 'seccion', '1', 'c1', 'Introducción', 1);
SET @seccion_id := LAST_INSERT_ID();

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '1.1', 'Fundamentación constitucional: autonomía parlamentaria', '<p>El personal de las Cortes Generales se encuadra en la organización administrativa propia del Congreso de los Diputados y del Senado. Su régimen jurídico se fundamenta en la autonomía parlamentaria, que asegura la independencia de las Cámaras respecto de los demás poderes del Estado y permite el ejercicio efectivo de sus funciones constitucionales.</p><p>Las Cortes Generales representan al pueblo español, ejercen la potestad legislativa del Estado, aprueban los Presupuestos Generales del Estado y controlan la acción del Gobierno, conforme al <span class="uji-ref" data-norma="CE" data-arts="66">art. 66 CE</span>. Estas funciones requieren una Administración parlamentaria profesional, estable y especializada, capaz de proporcionar apoyo jurídico, técnico, documental, administrativo, económico, protocolario, operativo y de seguridad interna.</p><p>La norma constitucional central es el <span class="uji-ref" data-norma="CE" data-arts="72.1">art. 72.1 CE</span>, que reconoce que las Cámaras establecen sus propios Reglamentos, aprueban autónomamente sus presupuestos y, de común acuerdo, regulan el Estatuto del Personal de las Cortes Generales.</p><p>De este precepto se deriva una autonomía parlamentaria con tres manifestaciones principales:</p><ul class="uji-lista"><li>autonomía normativa, mediante la aprobación de los Reglamentos parlamentarios</li><li>autonomía presupuestaria, mediante la aprobación autónoma de los presupuestos</li><li>autonomía de personal, mediante la regulación conjunta del Estatuto del Personal</li></ul><p>Esta autonomía no implica que las Cámaras queden fuera del ordenamiento jurídico, sino que cuentan con un régimen propio de organización y de empleo público, sujeto a la Constitución y a las normas específicamente aplicables al ámbito parlamentario.</p>', 1);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '1.2', 'Singularidad del régimen jurídico del personal de las Cortes Generales', '<p>La Administración parlamentaria no forma parte de la Administración General del Estado ni está sometida a la dirección del Gobierno. Depende de las Presidencias, de las Mesas y de las Secretarías Generales de las Cámaras, de conformidad con las normas parlamentarias y con el Estatuto del Personal de las Cortes Generales.</p><p>La singularidad de esta Administración se explica por las características de la actividad parlamentaria:</p><ul class="uji-lista"><li>asistencia a órganos constitucionales</li><li>elaboración y tramitación de iniciativas parlamentarias</li><li>apoyo a los procedimientos legislativos</li><li>asesoramiento jurídico y técnico</li><li>organización de Plenos, Comisiones, Ponencias y otros órganos</li><li>gestión documental y bibliográfica</li><li>redacción y publicación del Diario de Sesiones</li><li>administración presupuestaria y de personal</li><li>funcionamiento material de las sedes parlamentarias</li><li>control de accesos, orientación, custodia y apoyo a los trabajos de las Cámaras</li></ul><p>El personal de las Cortes Generales se rige prioritariamente por su Estatuto específico. El régimen general de la función pública estatal solo resulta aplicable cuando así lo prevea expresamente el Estatuto o de forma supletoria, siempre que sea compatible con la autonomía parlamentaria.</p>', 2);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '1.3', 'El Estatuto del Personal de las Cortes Generales vigente', '<p>La norma básica vigente es el Acuerdo de 20 de noviembre de 2025, adoptado por las Mesas del Congreso de los Diputados y del Senado en reunión conjunta, por el que se aprueba el Estatuto del Personal de las Cortes Generales.</p><p>Este Estatuto actualiza de forma integral el marco jurídico aplicable al personal parlamentario. Mantiene los principios estructurales tradicionales de profesionalidad, estabilidad, mérito, capacidad y especialización, pero incorpora medidas orientadas a modernizar la Administración parlamentaria.</p><p>Entre las novedades más relevantes destacan:</p><ul class="uji-lista"><li>el refuerzo de las medidas de igualdad en el acceso y permanencia</li><li>la ampliación y actualización de permisos y medidas de conciliación</li><li>el reconocimiento de nuevas modalidades de prestación de servicios</li><li>la introducción expresa de la carrera horizontal</li><li>una nueva regulación de la promoción interna</li><li>la actualización de las situaciones administrativas</li><li>la adaptación a la coexistencia de regímenes de Clases Pasivas y Seguridad Social</li><li>el reforzamiento de la formación continua</li><li>la regulación más detallada de derechos de representación, negociación y participación</li><li>y la modernización de las reglas retributivas, de provisión y de carrera profesional</li></ul>', 3);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '1.4', 'Aprobación, entrada en vigor y derogación del régimen anterior', '<p>El Estatuto vigente fue aprobado por las Mesas del Congreso y del Senado en reunión conjunta de 20 de noviembre de 2025 y publicado en el Boletín Oficial de las Cortes Generales el 21 de noviembre de 2025.</p><p>Su entrada en vigor se produjo al día siguiente de su publicación. Sin embargo, las disposiciones relativas al régimen de retribuciones producen efectos desde el 1 de enero de 2026.</p><p>La disposición derogatoria del Estatuto deja sin efecto las normas de igual o inferior rango que se opongan a su contenido y deroga expresamente:</p><ul class="uji-lista"><li>el Estatuto del Personal de las Cortes Generales aprobado en 2006</li><li>las modificaciones aprobadas en 2008 y 2009</li><li>y las modificaciones relativas a titulaciones aprobadas en 2016</li></ul><p>Por ello, no resultan aplicables las referencias del Estatuto de 2006 cuando contradigan o hayan sido sustituidas por la regulación vigente de 2025. En especial, deben actualizarse las reglas sobre promoción interna, régimen de jubilación, permisos, carrera profesional, Cuerpo de Redactores, situaciones administrativas y representación del personal.</p>', 4);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '1.5', 'Estructura sistemática del Estatuto de 2025', '<p>El Estatuto se distribuye en ocho capítulos:</p><ol class="uji-lista"><li>Del personal de las Cortes Generales: arts. 1 a 6.</li><li>Del personal funcionario de las Cortes Generales: arts. 7 y 8.</li><li>Del ingreso y cese del personal funcionario: arts. 9 a 16.</li><li>De las situaciones del personal funcionario: arts. 17 a 29.</li><li>De los derechos del personal funcionario: arts. 30 a 64.</li><li>De los deberes e incompatibilidades del personal funcionario: arts. 65 a 76.</li><li>Del régimen disciplinario: arts. 77 a 84.</li><li>De la eficacia e impugnación de las resoluciones adoptadas en materia de personal: arts. 85 y 86.</li></ol><p>El texto se completa con disposiciones adicionales, transitorias, derogatoria y final.</p><p>Este tema se centra en las materias propias de su primer bloque: clases de personal, organización, Cuerpos, ingreso y cese, y situaciones administrativas.</p>', 5);

-- ================= SECCIÓN 2. Personal de las Cortes Generales: clases y órganos competentes
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, color_clase, titulo, orden)
VALUES (@tema_id, NULL, 'seccion', '2', 'c2', 'Personal de las Cortes Generales: clases y órganos competentes', 2);
SET @seccion_id := LAST_INSERT_ID();

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '2.1', 'Consideraciones generales', '<p>El Estatuto distingue cuatro categorías de personal:</p><ol class="uji-lista"><li>Personal funcionario de las Cortes Generales.</li><li>Personal eventual.</li><li>Personal perteneciente a Cuerpos de la Administración General del Estado adscrito a las Cámaras.</li><li>Personal laboral.</li></ol><p>La categoría principal es la del personal funcionario de las Cortes Generales. Constituye el núcleo profesional permanente de la Administración parlamentaria y desarrolla las funciones que el Estatuto atribuye a los distintos Cuerpos.</p><p>Las demás modalidades responden a necesidades específicas: confianza y asistencia directa en el caso del personal eventual; seguridad o funciones no atribuidas a los Cuerpos de las Cortes en el caso del personal procedente de la Administración General del Estado; y funciones no reservadas estatutariamente a los Cuerpos funcionariales en el caso del personal laboral.</p>', 1);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '2.2', 'Personal funcionario de las Cortes Generales', '<p>El <span class="uji-ref" data-norma="EPCG" data-arts="1">art. 1 del Estatuto</span> define al personal funcionario de las Cortes Generales como aquel que, en virtud de nombramiento legal, se halle incorporado a las mismas con carácter permanente, mediante una relación estatutaria de servicios profesionales y retribuidos con cargo al presupuesto de aquellas.</p><p>Conforme al <span class="uji-ref" data-norma="EPCG" data-arts="7.2">art. 7.2 del Estatuto</span>, el personal funcionario puede prestar servicio en:</p><ul class="uji-lista"><li>el Congreso de los Diputados</li><li>el Senado</li><li>los Servicios Comunes de las Cortes Generales</li><li>la Junta Electoral Central</li></ul><p>La prestación se realiza mediante el desempeño de puestos incluidos en las correspondientes plantillas orgánicas.</p><p>De esta definición derivan cinco notas esenciales:</p>', 2);
SET @epigrafe_id := LAST_INSERT_ID();
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.2', 'a', 'Nombramiento legal', '<p>La incorporación se produce mediante nombramiento formal, previa superación del correspondiente proceso selectivo y cumplimiento de los requisitos estatutarios.</p>', 1);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.2', 'b', 'Carácter permanente', '<p>El vínculo funcionarial tiene vocación de estabilidad. No es una relación temporal ni una prestación ocasional vinculada a un cargo de confianza.</p>', 2);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.2', 'c', 'Relación estatutaria', '<p>La relación de servicio se rige por normas de Derecho público, especialmente por el Estatuto del Personal de las Cortes Generales y por sus disposiciones de desarrollo.</p>', 3);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.2', 'd', 'Profesionalidad', '<p>El personal funcionario desempeña funciones profesionales dirigidas al apoyo, organización y continuidad de las actividades parlamentarias y administrativas de las Cámaras.</p>', 4);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.2', 'e', 'Retribución presupuestaria', '<p>Las retribuciones se financian con cargo a los presupuestos propios de las Cortes Generales, en coherencia con su autonomía presupuestaria.</p>', 5);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '2.3', 'Personal eventual', '<p>El personal eventual se regula en el <span class="uji-ref" data-norma="EPCG" data-arts="2">art. 2 del Estatuto</span>. Su función es la asistencia directa y de confianza a las personas miembros de las Mesas y a otros parlamentarios o parlamentarias que aquellas determinen.</p><p>Los Grupos Parlamentarios pueden contar con personal eventual dentro del número que determine la Mesa de cada Cámara.</p><p>Sus notas principales son las siguientes:</p>', 3);
SET @epigrafe_id := LAST_INSERT_ID();
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.3', 'a', 'Asistencia directa y de confianza', '<p>Su función no es la de ocupar puestos estructurales de la Administración parlamentaria, sino prestar apoyo de carácter fiduciario y directo a los órganos o parlamentarios a los que se encuentre adscrito.</p>', 1);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.3', 'b', 'Libre nombramiento y libre separación', '<p>Es nombrado y separado libremente por la Presidencia de cada Cámara, a propuesta de la persona titular del órgano de adscripción.</p>', 2);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.3', 'c', 'Cese automático', '<p>Cesa automáticamente cuando cesa la persona titular del órgano al que sirve. Se trata de una consecuencia lógica del carácter de confianza del vínculo.</p><p>No obstante, durante los períodos de disolución de las Cámaras, las Mesas pueden adoptar las medidas provisionales que estimen oportunas.</p>', 3);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.3', 'd', 'Aplicación limitada del Estatuto', '<p>Al personal eventual se le aplica el régimen general previsto para el personal funcionario únicamente cuando no se oponga a la naturaleza de sus funciones.</p>', 4);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.3', 'e', 'Prohibición de ejercer funciones propias del personal funcionario', '<p>No puede ocupar puestos de trabajo ni desempeñar funciones propias del personal funcionario de las Cortes Generales. Esta regla garantiza que las funciones estructurales y profesionales de la Administración parlamentaria sean desarrolladas por personal seleccionado conforme a los principios de igualdad, mérito y capacidad.</p>', 5);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.3', 'f', 'Retribuciones', '<p>Las retribuciones se determinan en el presupuesto de cada Cámara.</p>', 6);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '2.4', 'Personal perteneciente a Cuerpos de la Administración General del Estado', '<p>El <span class="uji-ref" data-norma="EPCG" data-arts="3">art. 3 del Estatuto</span> prevé que las Cámaras puedan solicitar del Gobierno la adscripción de personal perteneciente a Cuerpos de la Administración General del Estado.</p><p>La adscripción se puede solicitar para:</p><ul class="uji-lista"><li>el desempeño de funciones de seguridad</li><li>y el desarrollo de otras funciones no atribuidas estatutariamente a los Cuerpos de personal funcionario de las Cortes Generales</li></ul><p>Este personal conserva su pertenencia a los Cuerpos de origen y se mantiene en situación de servicio activo en ellos. Sin embargo, mientras presta servicio en las Cortes Generales, depende de la Presidencia y de la Secretaría General de la Cámara en la que se encuentre destinado.</p><p>La disposición adicional primera añade que este personal se rige por la legislación de funcionarios civiles del Estado. No obstante, queda sometido jerárquicamente a la Presidencia y a la Secretaría General de la Cámara respecto del desarrollo de sus funciones, y puede percibir incentivos con cargo al presupuesto de la Cámara a la que esté adscrito.</p>', 4);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '2.5', 'Personal laboral', '<p>El <span class="uji-ref" data-norma="EPCG" data-arts="4">art. 4</span> permite al Congreso y al Senado contratar personal laboral para funciones que no estén atribuidas estatutariamente a los Cuerpos de personal funcionario de las Cortes Generales.</p><p>La contratación laboral debe ajustarse a dos exigencias:</p><ul class="uji-lista"><li>los puestos deben estar previstos como laborales en las plantillas orgánicas</li><li>las funciones no pueden estar reservadas a los Cuerpos funcionariales</li></ul><p>El personal laboral es contratado por cada Cámara y se retribuye con cargo a los créditos presupuestarios correspondientes.</p><p>La selección se determina por las Mesas de cada Cámara y ha de respetar necesariamente los principios de:</p><ul class="uji-lista"><li>publicidad</li><li>igualdad</li><li>mérito</li><li>capacidad</li></ul>', 5);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '2.6', 'Órganos competentes en materia de personal', '<p>El <span class="uji-ref" data-norma="EPCG" data-arts="5">art. 5</span> atribuye las competencias de personal a:</p><ul class="uji-lista"><li>las Presidencias del Congreso y del Senado</li><li>las Mesas de las Cámaras, actuando conjunta o separadamente</li><li>los órganos competentes de las Secretarías Generales</li><li>y la Junta de Personal, en los supuestos y con el alcance previstos en el Estatuto</li></ul><p>La distribución competencial se corresponde con la estructura bicameral de las Cortes Generales. Hay materias propias de cada Cámara y otras que, por afectar al régimen común, a los Servicios Comunes o a la unidad del Estatuto, requieren la actuación conjunta de las Mesas.</p><p>Entre las competencias de las Mesas reunidas conjuntamente destacan, por ejemplo:</p><ul class="uji-lista"><li>la aprobación y modificación del Estatuto</li><li>la aprobación de la oferta de empleo público y de los planes de empleo</li><li>la aprobación de determinados elementos retributivos</li><li>la aprobación de las plantillas de los Servicios Comunes y de la Junta Electoral Central</li><li>la aprobación del desarrollo normativo del Estatuto</li><li>la resolución de determinados recursos</li><li>y la ratificación de los acuerdos alcanzados en la Mesa Negociadora</li></ul>', 6);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '2.7', 'Secretarías Generales, Letrado o Letrada Mayor y órganos adjuntos', '<p>El <span class="uji-ref" data-norma="EPCG" data-arts="6">art. 6</span> regula las figuras superiores de la Administración parlamentaria.</p>', 7);
SET @epigrafe_id := LAST_INSERT_ID();
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.7', 'a', 'Secretaría General del Congreso y Letrado o Letrada Mayor del Senado', '<p>La persona titular de la Secretaría General del Congreso y la persona titular de la Letrada o Letrado Mayor del Senado son nombradas o, en su caso, ratificadas por la Mesa de cada Cámara, a propuesta de la Presidencia respectiva, en cada legislatura o cuando exista vacante.</p><p>Deben ser miembros del Cuerpo de Letrados de las Cortes Generales con más de cinco años de servicio activo.</p>', 1);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.7', 'b', 'Adjuntos', '<p>Los Secretarios o Secretarias Generales Adjuntos del Congreso y los Letrados o Letradas Mayores Adjuntos del Senado son nombrados por las Mesas respectivas, a propuesta de la Secretaría General del Congreso o de la Letrada o Letrado Mayor del Senado.</p><p>Han de pertenecer al Cuerpo de Letrados de las Cortes Generales.</p>', 2);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.7', 'c', 'Cese', '<p>Cesan por:</p><ul class="uji-lista"><li>renuncia</li><li>decisión del órgano que realizó el nombramiento</li><li>pérdida de la condición de personal funcionario</li><li>pase a una situación administrativa distinta de la de servicio activo</li><li>imposibilidad para el desempeño del cargo</li></ul>', 3);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '2.7', 'd', 'Letrado o Letrada Mayor de las Cortes Generales', '<p>Con carácter ordinario, la persona titular de la Secretaría General del Congreso ostenta el cargo de Letrado o Letrada Mayor de las Cortes Generales.</p><p>Sin embargo, las Mesas de ambas Cámaras, en reunión conjunta, pueden decidir que este cargo se provea independientemente entre miembros del Cuerpo de Letrados con más de cinco años de servicio activo.</p><p>Estas figuras concentran funciones de dirección superior, interpretación normativa, asesoramiento y gestión de la Administración parlamentaria.</p>', 4);

-- ================= SECCIÓN 3. Personal funcionario: Cuerpos y funciones
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, color_clase, titulo, orden)
VALUES (@tema_id, NULL, 'seccion', '3', 'c3', 'Personal funcionario: Cuerpos y funciones', 3);
SET @seccion_id := LAST_INSERT_ID();

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '3.1', 'Cuerpos de personal funcionario de las Cortes Generales', '<p>El <span class="uji-ref" data-norma="EPCG" data-arts="7">art. 7 del Estatuto</span> enumera los siguientes Cuerpos:</p><ol class="uji-lista"><li>Cuerpo de Letrados de las Cortes Generales.</li><li>Cuerpo de Archiveros-Bibliotecarios de las Cortes Generales.</li><li>Cuerpo de Asesores Facultativos de las Cortes Generales.</li><li>Cuerpo de Redactores de las Cortes Generales.</li><li>Cuerpo Técnico-Administrativo de las Cortes Generales.</li><li>Cuerpo Administrativo de las Cortes Generales.</li><li>Cuerpo de Ujieres de las Cortes Generales.</li></ol><p>La adscripción a un Cuerpo determina el ámbito general de funciones que puede desempeñar cada funcionario o funcionaria, sin perjuicio de las funciones específicas asignadas a cada puesto en las plantillas orgánicas.</p>', 1);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '3.2', 'Cuerpo de Letrados', '<p>El Cuerpo de Letrados desarrolla funciones de asesoramiento jurídico, técnico y parlamentario de máximo nivel.</p><p>Le corresponde:</p><ul class="uji-lista"><li>asesorar jurídicamente y técnicamente a las Presidencias, Mesas y Juntas de Portavoces</li><li>asistir a Comisiones, Subcomisiones, Ponencias y otros órganos parlamentarios</li><li>redactar resoluciones, informes y dictámenes conforme a los acuerdos de los órganos</li><li>levantar las actas correspondientes</li><li>asumir la representación y defensa de las Cortes Generales, Congreso, Senado, Junta Electoral Central y órganos vinculados o dependientes ante los órganos jurisdiccionales y el Tribunal Constitucional</li><li>asesorar en relaciones internacionales e institucionales</li><li>realizar funciones de estudio y propuesta de nivel superior</li><li>dirigir la Administración parlamentaria y asumir la titularidad de sus órganos de dirección</li></ul><p>La función del Cuerpo de Letrados es esencial para asegurar la regularidad jurídica de la actividad parlamentaria y administrativa.</p>', 2);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '3.3', 'Cuerpo de Archiveros-Bibliotecarios', '<p>El Cuerpo de Archiveros-Bibliotecarios se ocupa de la organización y gestión de la información, documentación y patrimonio bibliográfico de las Cámaras.</p><p>Le corresponde:</p><ul class="uji-lista"><li>organizar y gestionar recursos documentales y bibliográficos</li><li>tratar y analizar documentos</li><li>difundir los recursos a través de los órganos competentes</li><li>cuidar, conservar y preservar el patrimonio documental y bibliográfico de las Cortes Generales</li><li>realizar tareas de asistencia, asesoramiento, informe, estudio y propuesta de nivel superior</li><li>ejercer la jefatura de los servicios correspondientes</li><li>y desarrollar funciones directivas en materias de su especialidad, según las plantillas orgánicas</li></ul>', 3);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '3.4', 'Cuerpo de Asesores Facultativos', '<p>El Cuerpo de Asesores Facultativos desempeña las funciones superiores de asistencia, asesoramiento, informe, estudio y propuesta dentro de las materias propias de su especialidad.</p><p>También puede ejercer:</p><ul class="uji-lista"><li>jefaturas de los servicios correspondientes</li><li>funciones de dirección en materias propias de cada especialidad, conforme a las plantillas orgánicas</li></ul><p>La especialización de este Cuerpo permite cubrir necesidades técnicas de las Cámaras en ámbitos como economía, comunicación, ingeniería, arquitectura, informática, sociología u otras disciplinas.</p>', 4);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '3.5', 'Cuerpo de Redactores', '<p>El Estatuto vigente denomina a este Cuerpo Cuerpo de Redactores de las Cortes Generales, sustituyendo la anterior denominación de Cuerpo de Redactores Taquígrafos y Estenotipistas.</p><p>Sus funciones son:</p><ul class="uji-lista"><li>asistir a la reproducción íntegra de las intervenciones y hechos ocurridos en Plenos, Comisiones, Diputaciones Permanentes y, en su caso, otros órganos de las Cámaras</li><li>redactar, editar y publicar el Diario de Sesiones</li><li>ejercer la jefatura de los servicios correspondientes en los términos previstos en las plantillas orgánicas</li></ul><p>Este Cuerpo garantiza la documentación oficial y la publicidad de la actividad parlamentaria.</p>', 5);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '3.6', 'Cuerpo Técnico-Administrativo', '<p>El Cuerpo Técnico-Administrativo asume las funciones de:</p><ul class="uji-lista"><li>gestión administrativa</li><li>gestión económico-presupuestaria</li><li>gestión parlamentaria</li><li>ejecución, ordenación, inspección e impulso de procedimientos</li><li>estudio y propuesta de carácter técnico-administrativo</li><li>jefatura de servicios conforme a las plantillas orgánicas</li></ul><p>Se sitúa en un nivel de gestión técnica y de impulso de la actividad administrativa y parlamentaria de las Cortes.</p>', 6);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '3.7', 'Cuerpo Administrativo', '<p>El Cuerpo Administrativo desempeña:</p><ul class="uji-lista"><li>tareas administrativas de trámite</li><li>apoyo a funciones de gestión, ejecución, estudio y propuesta administrativa</li><li>tramitación administrativa, parlamentaria y económico-presupuestaria</li><li>utilización de aplicaciones informáticas de gestión</li><li>registro, clasificación, transcripción y archivo de documentos</li><li>atención y responsabilidad de secretarías</li><li>jefatura de unidades administrativas determinadas en las plantillas orgánicas</li></ul>', 7);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '3.8', 'Cuerpo de Ujieres', '<p>El Cuerpo de Ujieres realiza funciones vinculadas al funcionamiento material, operativo y protocolario de las sedes parlamentarias.</p><p>Le corresponde:</p><ul class="uji-lista"><li>vigilancia, control de accesos y custodia en el interior de los edificios parlamentarios</li><li>control del tránsito interno</li><li>orientación y acompañamiento de personas</li><li>asistencia y auxilio durante las reuniones de los órganos parlamentarios</li><li>colaboración en actividades protocolarias</li><li>reproducción, traslado y distribución de documentos, objetos y otros elementos análogos</li><li>apoyo a las unidades administrativas en los servicios especiales de destino</li><li>jefatura de unidades en los términos fijados por las plantillas orgánicas</li></ul><p>Estas funciones se desempeñan sin perjuicio de las propias del personal de seguridad adscrito desde la Administración General del Estado conforme al <span class="uji-ref" data-norma="EPCG" data-arts="3">art. 3 del Estatuto</span>.</p>', 8);

-- ================= SECCIÓN 4. Ingreso, adquisición, pérdida y jubilación
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, color_clase, titulo, orden)
VALUES (@tema_id, NULL, 'seccion', '4', 'c4', 'Ingreso, adquisición, pérdida y jubilación', 4);
SET @seccion_id := LAST_INSERT_ID();

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '4.1', 'Principios rectores de acceso', '<p>El acceso a la condición de personal funcionario de las Cortes Generales se rige por los principios de:</p><ul class="uji-lista"><li>igualdad</li><li>mérito</li><li>capacidad</li></ul><p>El Estatuto incorpora expresamente el principio de igualdad de oportunidades y compensación de desventajas en el acceso de las personas con discapacidad, con la posible adaptación de las bases de las convocatorias.</p><p>El acceso ha de realizarse con pleno respeto a la igualdad y sin discriminaciones por razones personales o sociales.</p>', 1);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '4.2', 'Requisitos de admisión a las pruebas selectivas', '<p>Para ser admitido a las pruebas selectivas se requiere:</p><ol class="uji-lista" type="a"><li>Poseer nacionalidad española y ser mayor de edad.</li><li>Estar en posesión de la titulación exigida, o en condiciones de obtenerla dentro del plazo de presentación de solicitudes.</li><li>No estar inhabilitado para el ejercicio de las funciones públicas por sentencia firme.</li><li>Reunir las condiciones psicofísicas necesarias para el desempeño de las funciones.</li><li>Cumplir los requisitos establecidos en cada convocatoria.</li></ol><p>Las convocatorias no pueden establecer requisitos discriminatorios por razón de raza, sexo, religión, opinión, lugar de nacimiento, vecindad o cualquier otra circunstancia personal o social. Tampoco pueden incluir preguntas sobre ideología, religión o creencias de las personas aspirantes.</p>', 2);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '4.3', 'Ingreso en los Cuerpos de las Cortes Generales', '<p>El ingreso se realiza mediante convocatoria pública, libre y oposición.</p><p>La convocatoria se efectúa en ejecución de:</p><ul class="uji-lista"><li>la oferta de empleo público anual</li><li>sus actualizaciones</li><li>y los planes de empleo plurianuales</li></ul><p>La aprobación de dichos instrumentos corresponde a las Mesas de ambas Cámaras en reunión conjunta, previo cumplimiento de las reglas de negociación colectiva previstas estatutariamente.</p><p>La oferta de empleo público debe garantizar una adecuada dotación de los Cuerpos para asegurar el correcto funcionamiento de las Secretarías Generales y facilitar la carrera administrativa.</p><p>Las titulaciones exigidas son:</p><ul class="uji-lista"><li>Letrados: Licenciatura o Grado en Derecho.</li><li>Archiveros-Bibliotecarios: Licenciatura o Grado en Artes, Humanidades o Ciencias Sociales y Jurídicas.</li><li>Asesores Facultativos: titulación superior correspondiente a la especialidad exigida por cada convocatoria.</li><li>Redactores: Diplomatura universitaria o Grado.</li><li>Técnico-Administrativo: Diplomatura universitaria o Grado.</li><li>Administrativo: Bachiller o equivalente.</li><li>Ujieres: Graduado en Educación Secundaria Obligatoria o equivalente.</li></ul>', 3);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '4.4', 'Turno restringido y reserva de plazas', '<p>En cada convocatoria se reserva un 25 % de las plazas para su provisión mediante turno restringido entre personal de otros Cuerpos de las Cortes Generales que posea la titulación exigida.</p><p>Si el porcentaje produce una fracción igual o superior a 0,5, se incrementa en una unidad el número de plazas reservadas, salvo que la convocatoria tenga menos de tres plazas, caso en el que todas corresponden al turno libre.</p><p>Las plazas de turno restringido que no se cubran se incorporan al turno libre.</p><p>Existe además una reserva del 10 % de las plazas para personas con discapacidad de grado igual o superior al 33 %, siempre que reúnan los requisitos de la convocatoria, superen las pruebas y acrediten la compatibilidad con las funciones.</p><p>Cuando la aplicación del porcentaje sea inferior a una plaza, se reserva una plaza si la convocatoria incluye al menos tres plazas.</p>', 4);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '4.5', 'Promoción interna', '<p>El Estatuto de 2025 refuerza la promoción interna.</p><p>Antes de cada convocatoria de oposición se realizará una convocatoria de plazas reservadas para promoción interna cuando la oferta anual correspondiente al Cuerpo incluya diez o más plazas. Excepcionalmente, puede reservarse promoción interna cuando el número sea inferior.</p><p>Pueden participar funcionarios de Cuerpos inmediatamente inferiores que:</p><ul class="uji-lista"><li>cuenten con al menos dos años de servicio activo en el Cuerpo de origen</li><li>y posean la titulación exigida</li></ul><p>Las Mesas de las Cámaras concretan en cada convocatoria:</p><ul class="uji-lista"><li>el número de plazas</li><li>los Cuerpos que pueden participar</li><li>y las condiciones aplicables</li></ul><p>El procedimiento puede ser de oposición o de concurso-oposición. Se excluyen del temario las materias cuyo conocimiento ya haya quedado acreditado con el ingreso en el Cuerpo de origen.</p><p>Quienes accedan por promoción interna tienen preferencia para cubrir las vacantes ofertadas respecto de quienes accedan por turno libre.</p>', 5);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '4.6', 'Formación y perfeccionamiento', '<p>Las Cortes Generales organizan y patrocinan cursos de formación y perfeccionamiento para facilitar la promoción del personal y mejorar la prestación de los servicios.</p><p>En las Secretarías Generales existe una unidad de formación encargada de ejecutar la política formativa de las Cámaras.</p><p>La Junta de Personal participa en los planes de formación en los términos establecidos por el Estatuto.</p><p>También pueden concederse permisos para realizar estudios directamente vinculados con la función pública parlamentaria. Requieren:</p><ul class="uji-lista"><li>informe del superior jerárquico</li><li>autorización de la Secretaría General correspondiente</li></ul><p>Durante un plazo máximo de un año, el personal autorizado puede percibir el 50 % del sueldo y de las retribuciones por antigüedad.</p>', 6);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '4.7', 'Adquisición de la condición de personal funcionario', '<p>La condición se adquiere por el cumplimiento sucesivo de estos requisitos:</p><ol class="uji-lista"><li>Superación de las pruebas selectivas.</li><li>Nombramiento conjunto por las Presidencias del Congreso y del Senado.</li><li>Juramento o promesa de acatamiento a la Constitución, obediencia a las leyes y ejercicio imparcial de las funciones.</li><li>Toma de posesión dentro del plazo de un mes desde la notificación del nombramiento.</li></ol>', 7);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '4.8', 'Pérdida de la condición de personal funcionario', '<p>La condición de personal funcionario se pierde por:</p><ol class="uji-lista" type="a"><li>Renuncia, que no impide un nuevo ingreso en la función pública.</li><li>Pérdida de la nacionalidad española.</li><li>Sanción disciplinaria de separación del servicio.</li><li>Pena principal o accesoria de inhabilitación absoluta o especial para cargos públicos.</li><li>Jubilación forzosa o voluntaria.</li></ol><p>En caso de pérdida de la condición funcionarial por pérdida de nacionalidad, la recuperación de esta permite solicitar la rehabilitación ante el Letrado o Letrada Mayor de las Cortes Generales.</p><p>También puede acordarse excepcionalmente la rehabilitación de quien hubiera perdido la condición funcionarial por condena de inhabilitación, atendiendo a las circunstancias y a la naturaleza y entidad del delito.</p>', 8);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '4.9', 'Jubilación', '<p>La jubilación se regula en el <span class="uji-ref" data-norma="EPCG" data-arts="16">art. 16 del Estatuto</span> vigente.</p>', 9);
SET @epigrafe_id := LAST_INSERT_ID();
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '4.9', 'a', 'Jubilación forzosa', '<p>La jubilación forzosa se declara de oficio al cumplirse la edad legalmente establecida según el régimen de Seguridad Social aplicable.</p><p>Para el personal incluido en el régimen de Clases Pasivas, la jubilación forzosa se produce al cumplir 65 años.</p>', 1);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '4.9', 'b', 'Prolongación voluntaria', '<p>El personal puede prolongar voluntariamente su permanencia en servicio activo hasta los 70 años, mediante escrito dirigido al Letrado o Letrada Mayor de las Cortes Generales y con una antelación mínima de dos meses respecto de la fecha de jubilación forzosa.</p><p>Una vez solicitada, la prórroga puede ser renunciada con tres meses de antelación a la fecha prevista de jubilación.</p>', 2);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '4.9', 'c', 'Prolongación hasta los 72 años', '<p>La permanencia puede prolongarse hasta los 72 años cuando se cumpla una de estas condiciones:</p><ul class="uji-lista"><li>quince años de servicio activo en las Cortes Generales, de los cuales los cinco últimos sean inmediatamente anteriores a la solicitud</li><li>o veinticinco años de servicio activo total</li></ul>', 3);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '4.9', 'd', 'Prórroga excepcional hasta los 75 años', '<p>Excepcionalmente, puede autorizarse una prórroga anual hasta los 75 años. La autorización corresponde a la Secretaría General del Congreso o a la Letrada o Letrado Mayor del Senado.</p><p>Requiere:</p><ul class="uji-lista"><li>solicitud del interesado</li><li>informe médico favorable sobre condiciones psicofísicas</li><li>informe favorable del superior jerárquico</li><li>resolución motivada</li></ul><p>La decisión debe atender a la trayectoria profesional, méritos, servicios que pueda prestar la persona, razones organizativas y funcionales y, especialmente, a necesidades de mentoría.</p>', 4);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '4.9', 'e', 'Limitación relativa a puestos con complemento de destino', '<p>No se puede ocupar un puesto con complemento de destino desde los 67 años, salvo si aún no se ha consolidado el porcentaje máximo previsto, y sin superar en ningún caso los 70 años.</p><p>Las Secretarías Generales deben adscribir al personal afectado a una plaza básica, atendiendo a su experiencia y a las necesidades del servicio.</p><p>La disposición transitoria novena difiere la efectividad de esta regla durante cuatro años desde la entrada en vigor del Estatuto, con las particularidades que establece para quienes no hayan consolidado el complemento.</p>', 5);
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, letra, titulo, contenido_html, orden)
VALUES (@tema_id, @epigrafe_id, 'subapartado', '4.9', 'f', 'Jubilación por incapacidad y jubilación voluntaria', '<p>También procede la jubilación por incapacidad permanente para ejercer las funciones propias del Cuerpo. Exige expediente, iniciado de oficio o a instancia de la persona interesada, con audiencia.</p><p>En el régimen de Clases Pasivas, la jubilación voluntaria puede solicitarse al cumplir 60 años o al reunir 35 años de servicios efectivos en las Cortes Generales o en otros entes públicos, sin perjuicio de las reglas aplicables para el personal sometido al régimen de Seguridad Social.</p>', 6);

-- ================= SECCIÓN 5. Situaciones administrativas
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, color_clase, titulo, orden)
VALUES (@tema_id, NULL, 'seccion', '5', 'c5', 'Situaciones administrativas', 5);
SET @seccion_id := LAST_INSERT_ID();

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.1', 'Enumeración y finalidad', '<p>El personal funcionario de las Cortes Generales puede encontrarse en las siguientes situaciones administrativas:</p><ol class="uji-lista" type="a"><li>Servicio activo.</li><li>Servicios especiales.</li><li>Excedencia.</li><li>Expectativa de destino.</li><li>Suspensión de funciones.</li></ol><p>Las situaciones administrativas permiten adaptar el vínculo funcionarial a circunstancias de servicio público, acceso a cargos, cuidado familiar, incompatibilidades, protección frente a violencia, imposibilidad temporal de servicio o ejercicio de derechos.</p>', 1);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.2', 'Servicio activo', '<p>Se encuentra en servicio activo el personal funcionario:</p><ul class="uji-lista"><li>que ocupa un puesto adscrito a personal funcionario en las plantillas del Congreso, Senado, Servicios Comunes o Junta Electoral Central</li><li>que desempeña una comisión de servicios de duración no superior a seis meses en organismos internacionales, entidades públicas, Gobiernos extranjeros, programas de cooperación, órganos constitucionales, Parlamentos o Asambleas Legislativas autonómicas</li><li>o que accede a un cargo electivo en corporaciones locales conforme al régimen local, salvo que el cargo sea retribuido o de dedicación exclusiva</li></ul><p>El personal en servicio activo mantiene la plenitud de derechos, deberes y responsabilidades inherentes a su condición.</p>', 2);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.3', 'Servicios especiales', '<p>El pase a servicios especiales se produce, entre otros supuestos, cuando el personal funcionario:</p><ul class="uji-lista"><li>realiza una misión superior a seis meses en organismos internacionales, Gobiernos, entidades extranjeras, programas de cooperación, órganos constitucionales o Parlamentos</li><li>presta servicio en organizaciones internacionales o supranacionales</li><li>desarrolla su labor al servicio del Estado en el exterior</li><li>accede a cargos políticos o de confianza</li><li>es nombrado personal eventual del Congreso o del Senado</li><li>adquiere la condición de diputado, senador, miembro del Parlamento Europeo o de una Asamblea Legislativa autonómica</li><li>desempeña un cargo electivo local retribuido y de dedicación exclusiva</li><li>accede a cargos constitucionales o institucionales expresamente enumerados por el Estatuto</li><li>o cuando una ley determine expresamente el pase a esa situación</li></ul><p>El personal en servicios especiales tiene derecho a la reserva de una plaza básica del Cuerpo de pertenencia.</p><p>El tiempo en servicios especiales se computa para ascensos, antigüedad y derechos en Seguridad Social o Clases Pasivas. Puede participar en concursos de provisión de puestos en los términos estatutariamente establecidos.</p><p>No percibe las retribuciones ordinarias de las Cortes Generales, salvo las que correspondan por antigüedad.</p>', 3);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.4', 'Excedencia: régimen general', '<p>La excedencia puede declararse por:</p><ul class="uji-lista"><li>interés particular</li><li>prestación de servicios en el sector público</li><li>agrupación familiar</li><li>cuidado de hijos, hijas y familiares</li><li>violencia de género o sexual</li><li>violencia terrorista</li></ul><p>La excedencia requiere, con carácter general, petición de la persona interesada y se concede por la Secretaría General del Congreso o por la Letrada o Letrado Mayor del Senado, según la Cámara de destino, salvo la excepción prevista para la excedencia por interés particular derivada de falta de solicitud de reingreso.</p>', 4);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.5', 'Excedencia por interés particular', '<p>Puede concederse al personal que haya completado tres años de servicio activo desde su ingreso en las Cortes Generales.</p><p>La concesión queda subordinada a la buena marcha del servicio y no puede otorgarse a quien tenga un expediente disciplinario en curso o no haya cumplido una sanción anterior.</p><p>También se produce esta situación cuando, desaparecida la causa que justificó el pase a una situación distinta del servicio activo, no se solicita el reingreso en treinta días.</p><p>Durante esta excedencia:</p><ul class="uji-lista"><li>no se devengan retribuciones</li><li>no se computa el tiempo para ascensos</li><li>no se computa a efectos de antigüedad</li><li>no se computa a efectos de derechos de Seguridad Social o Clases Pasivas</li></ul>', 5);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.6', 'Excedencia por prestación de servicios en el sector público', '<p>Se declara cuando el personal funcionario pasa a servicio activo en otros Cuerpos de las Cortes Generales o en cualquier organismo público.</p><p>También se aplica si el personal funcionario pasa a prestar servicios como personal laboral del Congreso, Senado o cualquier entidad u organismo del sector público.</p><p>No procede en los casos de docencia, investigación u otros supuestos legalmente exceptuados que cuenten con autorización de compatibilidad y no determinen servicios especiales.</p><p>Sus efectos son los mismos que los de la excedencia por interés particular.</p>', 6);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.7', 'Excedencia por agrupación familiar', '<p>Puede concederse sin necesidad de acreditar tres años previos de servicio activo cuando el cónyuge o pareja de hecho resida en otra localidad por haber obtenido un puesto definitivo como funcionario de carrera o personal laboral fijo.</p><p>El puesto puede estar en cualquier Administración Pública, organismo público, entidad de derecho público, órgano constitucional, órgano jurisdiccional, institución análoga autonómica, Unión Europea u organización internacional.</p><p>Durante esta excedencia no se perciben retribuciones ni se computa el tiempo para ascensos, antigüedad o derechos de Seguridad Social o Clases Pasivas.</p>', 7);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.8', 'Excedencia para el cuidado de hijos, hijas y familiares', '<p>El personal funcionario tiene derecho a una excedencia de duración no superior a tres años para el cuidado de cada hijo o hija, por nacimiento, adopción, guarda con fines de adopción o acogimiento, temporal o permanente en los términos establecidos.</p><p>También puede solicitarse para atender al cónyuge, pareja de hecho registrada o familiar hasta el segundo grado de consanguinidad o afinidad que, por edad, accidente, enfermedad o discapacidad, no pueda valerse por sí mismo y no desempeñe actividad retribuida.</p><p>Es un derecho individual. Si dos personas funcionarias generan el derecho por el mismo sujeto causante, la Administración parlamentaria puede limitar el disfrute simultáneo por razones justificadas de funcionamiento del servicio.</p><p>La excedencia puede disfrutarse fraccionadamente, por períodos mínimos de tres meses, atendiendo a las necesidades del servicio.</p><p>Durante esta situación:</p><ul class="uji-lista"><li>se computa el tiempo a efectos de antigüedad, ascensos y derechos de Seguridad Social o Clases Pasivas</li><li>se puede participar en concursos de provisión</li><li>se puede participar en cursos de formación</li><li>se reserva el puesto de trabajo básico o específico obtenido por concurso durante un máximo de tres años</li></ul>', 8);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.9', 'Excedencia por violencia de género o sexual y por violencia terrorista', '<p>Las funcionarias víctimas de violencia de género o sexual pueden solicitar esta excedencia sin necesidad de servicios previos mínimos y sin plazo mínimo de permanencia.</p><p>Durante los dos primeros años tienen derecho a:</p><ul class="uji-lista"><li>reserva del puesto</li><li>cómputo de antigüedad</li><li>cómputo para ascensos</li><li>cómputo de derechos en Seguridad Social o Clases Pasivas</li></ul><p>Este período puede prorrogarse por períodos sucesivos de seis meses, hasta un máximo de dieciocho meses, si las actuaciones judiciales lo exigen.</p><p>Durante los cuatro primeros meses se mantienen las retribuciones íntegras y puede accederse a prestaciones del Fondo de Prestaciones Sociales de las Cortes Generales.</p><p>El personal que haya sufrido daños, amenazas o coacciones por terrorismo puede acceder a una excedencia en condiciones equivalentes, mientras resulte necesaria para garantizar su protección o asistencia social integral.</p>', 9);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.10', 'Expectativa de destino', '<p>La expectativa de destino se produce cuando resulta imposible el reingreso al servicio activo tras cesar en una situación de excedencia o suspensión firme.</p><p>Quien se encuentre en expectativa de destino:</p><ul class="uji-lista"><li>percibe las retribuciones básicas por sueldo y antigüedad</li><li>mantiene el cómputo del tiempo a efectos pasivos, de cotización y de antigüedad</li><li>permanece a disposición de las Cortes Generales para realizar suplencias o sustituciones propias de su Cuerpo</li></ul>', 10);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.11', 'Suspensión de funciones', '<p>La suspensión de funciones priva temporalmente del ejercicio de las funciones y de los derechos inherentes a la condición funcionarial.</p><p>Puede ser:</p><ul class="uji-lista"><li>provisional</li><li>firme</li></ul><p>La suspensión firme se declara por sentencia penal o por sanción disciplinaria, así como cuando la pena determine imposibilidad de desempeñar el puesto.</p><p>La suspensión provisional puede adoptarse como medida cautelar durante la tramitación de un proceso penal o expediente disciplinario.</p><p>La suspensión provisional en expediente disciplinario no puede exceder de seis meses, salvo paralización imputable a la persona interesada. Durante la suspensión provisional se perciben retribuciones básicas, pero no complementarias.</p><p>La suspensión firme por sanción disciplinaria no puede exceder de seis años. Si supera seis meses, determina la pérdida del puesto de trabajo.</p>', 11);

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '5.12', 'Reingreso al servicio activo', '<p>El reingreso del personal que no tenga plaza reservada requiere solicitud escrita presentada, al menos, quince días hábiles antes de la fecha prevista.</p><p>El reingreso se acuerda por el Letrado o Letrada Mayor de las Cortes Generales cuando exista puesto vacante. La adscripción provisional corresponde a la Secretaría General del Congreso, a la Letrada o Letrado Mayor del Senado o a la Letrada o Letrado Mayor de las Cortes Generales en el ámbito de los Servicios Comunes y de la Junta Electoral Central.</p><p>También se puede reingresar mediante participación y obtención de puesto en una convocatoria de provisión, por concurso o libre designación, adquiriéndose entonces plaza con carácter definitivo.</p>', 12);

-- ================= SECCIÓN 6. Cierre del tema
INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, color_clase, titulo, orden)
VALUES (@tema_id, NULL, 'seccion', '6', 'c6', 'Cierre del tema', 6);
SET @seccion_id := LAST_INSERT_ID();

INSERT INTO opouj_wp_uji_nodos (tema_id, parent_id, tipo, numero, titulo, contenido_html, orden)
VALUES (@tema_id, @seccion_id, 'epigrafe', '6.1', 'Recapitulación', '<p>El régimen del personal de las Cortes Generales se fundamenta en la autonomía parlamentaria del <span class="uji-ref" data-norma="CE" data-arts="72.1">art. 72.1 CE</span> y se regula, con carácter principal, por el Estatuto del Personal de las Cortes Generales de 2025.</p><p>Ese régimen configura una Administración parlamentaria propia, integrada fundamentalmente por personal funcionario especializado y organizada en siete Cuerpos profesionales. El acceso se rige por igualdad, mérito y capacidad; la carrera se articula mediante promoción interna, provisión de puestos y carrera horizontal; y el vínculo funcionarial se adapta a las circunstancias personales y profesionales a través de las distintas situaciones administrativas.</p><p>La especialización, estabilidad y neutralidad del personal parlamentario son garantías necesarias para la continuidad institucional, la autonomía de las Cámaras y el correcto ejercicio de las funciones constitucionales de las Cortes Generales.</p>', 1);

